apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/chanseok-playground-new/java-frontend
    jibMaven: {}
    context: java-frontend
  - image: gcr.io/chanseok-playground-new/groovy-backend
    jibGradle: {}
    context: groovy-backend
  - image: gcr.io/chanseok-playground-new/nodejs-backend
    context: nodejs-backend
    sync:
      '*.js': .
